name: MedicalDarkAge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3906832553911954
title: Medical Dark Age
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#302a1d'
    - '#847c57'
    - '#7b1a0a'
    - '#c2aa5f'
  brandStrength: 1
  lightness: 0.14151367777958512
  saturation: 1
  rhythmicContrast: 0.18888388411141932
purpose: []
