name: MedicalDarkAge
favicon: null
layout_spectrum: 0.23342
typography_spectrum: 0.49785
title: Medical Dark Age
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#302a1d'
    - '#847c57'
    - '#7b1a0a'
    - '#c2aa5f'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
